//! Chrome variant of the browser bridge setup.
//!
//! The bridge pipeline (CLI -> WebSocket -> native messaging host ->
//! extension) is browser-agnostic. This module only handles the Chrome-side
//! packaging: it transforms the downloaded Firefox `.xpi` into an unpacked
//! Chrome MV3 extension directory and registers the same native messaging
//! host for Chrome. The Firefox path in `crate::browser` is untouched.

use anyhow::{Context, Result};
use serde_json::{Value, json};
use std::path::{Path, PathBuf};

use crate::browser::{
    BrowserStatus, browser_binary_path, browser_dir, check_browser_ping, download_browser_binary,
    host_binary_path, probe_bridge_missing_actions, xpi_path,
};

/// Native messaging host name shared with the Firefox setup. The extension's
/// background script calls `connectNative("firefox_agent_bridge")`, so the
/// Chrome-side registration must use the same name.
const NATIVE_HOST_NAME: &str = "firefox_agent_bridge";

/// Fixed public key pinned into the generated manifest so the unpacked
/// extension always loads with the same extension ID. Unpacked extensions do
/// not need the matching private key; the key only determines the ID.
const CHROME_EXTENSION_KEY: &str = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnUGESdUL5/jfak67ojol/nYe3eRfP2ALyOE3F94YL+xFQHYOeT9gByVUtX6ZeLPMg1evVNPuOUnV5pZo59HMkZ5GTxZ21Bp3FWqRB8qNwAQPlGRqQGQOYDESIT+pLd8AlyYjINuJJPwKgxbl3K8n2dPF2y9g8pNg7bqyBqRXZTKRlgiUox0R3Nyahd8DxLqg9Loh3H+jX7fsWYUiA7yInSn7lef6hR21KZTuS/+BKVWTYCybv3GneaxtstkLJr/JzVMbTLE9jnG48owd2Ad5ELr5A99XnBaPgMs3eEyXB4QegFaqhIQitiBfJWem3qbsJJKh0T/6JXEbK8Xrmx8lmQIDAQAB";

/// Extension ID derived from `CHROME_EXTENSION_KEY` (first 16 bytes of the
/// SHA-256 of the DER SPKI, hex digits mapped 0-15 -> a-p).
pub const CHROME_EXTENSION_ID: &str = "ccfekfoninbngnemlgcnnicejjgbogln";

/// Compatibility shim loaded before the Firefox-flavored scripts. Provides a
/// `browser.*` namespace over `chrome.*`, maps `browserAction` to `action`,
/// lets `runtime.onMessage` listeners return Promises (Firefox semantics),
/// and round-trips content-script errors as rejections.
const BROWSER_SHIM_JS: &str = r#"// Generated by jcode: Firefox WebExtension API shim for Chrome MV3.
(() => {
  if (globalThis.browser && globalThis.browser.runtime) return;
  const c = globalThis.chrome;
  if (!c || !c.runtime) return;
  const ERR = "__agentBridgeShimError";
  const wrapOnMessage = (event) => ({
    addListener(listener) {
      event.addListener((msg, sender, sendResponse) => {
        let result;
        try {
          result = listener(msg, sender, sendResponse);
        } catch (err) {
          sendResponse({ [ERR]: String((err && err.message) || err) });
          return false;
        }
        if (result && typeof result.then === "function") {
          result.then(
            (value) => { try { sendResponse(value); } catch (_) {} },
            (err) => { try { sendResponse({ [ERR]: String((err && err.message) || err) }); } catch (_) {} },
          );
          return true;
        }
        return result === true;
      });
    },
    removeListener(listener) { event.removeListener(listener); },
    hasListener(listener) { return event.hasListener(listener); },
  });
  const rethrow = (value) => {
    if (value && typeof value === "object" && typeof value[ERR] === "string") {
      throw new Error(value[ERR]);
    }
    return value;
  };
  const bindNamespace = (ns, overrides) => new Proxy(ns, {
    get(target, prop) {
      if (overrides && prop in overrides) return overrides[prop];
      const value = target[prop];
      return typeof value === "function" ? value.bind(target) : value;
    },
  });
  const runtime = bindNamespace(c.runtime, {
    onMessage: wrapOnMessage(c.runtime.onMessage),
    sendMessage: async (...args) => rethrow(await c.runtime.sendMessage(...args)),
  });
  const tabs = c.tabs ? bindNamespace(c.tabs, {
    sendMessage: async (...args) => rethrow(await c.tabs.sendMessage(...args)),
  }) : undefined;
  globalThis.browser = new Proxy(c, {
    get(target, prop) {
      if (prop === "runtime") return runtime;
      if (prop === "tabs" && tabs) return tabs;
      if (prop === "browserAction") return c.action;
      return target[prop];
    },
  });
})();
"#;

pub fn chrome_extension_dir() -> PathBuf {
    browser_dir().join("chrome-extension")
}

fn chrome_host_manifest_path() -> PathBuf {
    browser_dir().join(format!("{}.chrome.json", NATIVE_HOST_NAME))
}

fn chrome_setup_marker_path() -> PathBuf {
    browser_dir().join(".setup-complete-chrome")
}

pub fn is_chrome_setup_complete() -> bool {
    chrome_setup_marker_path().exists()
        && chrome_extension_dir().join("manifest.json").exists()
        && browser_binary_path().exists()
        && host_binary_path().exists()
}

fn mark_chrome_setup_complete() -> Result<()> {
    std::fs::write(chrome_setup_marker_path(), chrono::Utc::now().to_rfc3339())?;
    Ok(())
}

/// Rewrite the Firefox MV2 manifest into a Chrome MV3 manifest for the
/// unpacked extension. Pure so it is directly testable.
fn build_mv3_manifest(orig: &Value) -> Value {
    let version = orig["version"].as_str().unwrap_or("0.0.0");
    let description = orig["description"].as_str().unwrap_or("");
    let icons = orig
        .get("icons")
        .cloned()
        .unwrap_or_else(|| json!({ "48": "icons/icon-48.png" }));
    json!({
        "manifest_version": 3,
        "name": "Browser Agent Bridge (Chrome)",
        "version": version,
        "description": description,
        "icons": icons,
        "permissions": [
            "tabs", "activeTab", "nativeMessaging", "notifications",
            "storage", "webNavigation", "downloads", "scripting"
        ],
        "host_permissions": ["<all_urls>"],
        "background": { "service_worker": "sw.js" },
        "content_scripts": [{
            "matches": ["<all_urls>"],
            "js": ["browser-shim.js", "content.js"],
            "run_at": "document_idle",
            "all_frames": true
        }],
        "action": {
            "default_icon": {
                "16": "icons/icon-16.png",
                "32": "icons/icon-32.png"
            },
            "default_title": "Browser Agent Bridge - Idle",
            "default_popup": "popup.html"
        },
        "key": CHROME_EXTENSION_KEY
    })
}

/// Extract the `.xpi` (a zip) into `dest` using tar (bsdtar, present on
/// Windows 10+ and macOS), with platform fallbacks.
fn extract_xpi_archive(xpi: &Path, dest: &Path) -> Result<()> {
    std::fs::create_dir_all(dest)?;
    let tar_ok = std::process::Command::new("tar")
        .arg("-xf")
        .arg(xpi)
        .arg("-C")
        .arg(dest)
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if tar_ok {
        return Ok(());
    }
    #[cfg(windows)]
    {
        // Expand-Archive insists on a .zip extension.
        let tmp_zip = dest.with_extension("src.zip");
        std::fs::copy(xpi, &tmp_zip)?;
        let status = std::process::Command::new("powershell")
            .args([
                "-NoProfile",
                "-Command",
                &format!(
                    "Expand-Archive -Force '{}' '{}'",
                    tmp_zip.display(),
                    dest.display()
                ),
            ])
            .status()
            .context("Failed to run Expand-Archive for the extension archive")?;
        let _ = std::fs::remove_file(&tmp_zip);
        if status.success() {
            return Ok(());
        }
    }
    #[cfg(not(windows))]
    {
        let status = std::process::Command::new("unzip")
            .arg("-o")
            .arg(xpi)
            .arg("-d")
            .arg(dest)
            .status()
            .context("Failed to run unzip for the extension archive")?;
        if status.success() {
            return Ok(());
        }
    }
    anyhow::bail!(
        "Could not extract the extension archive at {}",
        xpi.display()
    )
}

/// Build the unpacked Chrome extension directory from the downloaded `.xpi`.
pub fn generate_chrome_extension() -> Result<PathBuf> {
    let xpi = xpi_path();
    if !xpi.exists() {
        anyhow::bail!(
            "Extension archive not found at {}. Run browser setup first to download bridge assets.",
            xpi.display()
        );
    }

    let final_dir = chrome_extension_dir();
    let tmp_dir = browser_dir().join(format!(".chrome-extension.tmp-{}", std::process::id()));
    if tmp_dir.exists() {
        std::fs::remove_dir_all(&tmp_dir)?;
    }
    extract_xpi_archive(&xpi, &tmp_dir)?;

    // Signing metadata is Firefox-only.
    let meta_inf = tmp_dir.join("META-INF");
    if meta_inf.exists() {
        std::fs::remove_dir_all(&meta_inf)?;
    }

    let orig_manifest_path = tmp_dir.join("manifest.json");
    let orig: Value = serde_json::from_str(
        &std::fs::read_to_string(&orig_manifest_path)
            .context("Extracted extension has no manifest.json")?,
    )
    .context("Extracted manifest.json is not valid JSON")?;
    std::fs::write(
        &orig_manifest_path,
        serde_json::to_string_pretty(&build_mv3_manifest(&orig))?,
    )?;

    std::fs::write(tmp_dir.join("browser-shim.js"), BROWSER_SHIM_JS)?;
    std::fs::write(
        tmp_dir.join("sw.js"),
        "importScripts(\"browser-shim.js\", \"background.js\");\n",
    )?;

    // The popup also uses the `browser.*` namespace; load the shim first.
    let popup_path = tmp_dir.join("popup.html");
    if let Ok(popup) = std::fs::read_to_string(&popup_path) {
        let patched = popup.replace(
            "<script src=\"popup.js\"></script>",
            "<script src=\"browser-shim.js\"></script>\n  <script src=\"popup.js\"></script>",
        );
        std::fs::write(&popup_path, patched)?;
    }

    if final_dir.exists() {
        std::fs::remove_dir_all(&final_dir)?;
    }
    std::fs::rename(&tmp_dir, &final_dir)?;
    Ok(final_dir)
}

/// Install the Chrome native messaging host manifest (same host binary and
/// host name as the Firefox setup, but `allowed_origins` instead of
/// `allowed_extensions`). Returns true when something new was written.
pub fn install_chrome_native_host_manifest() -> Result<bool> {
    let host_path = host_binary_path();
    if !host_path.exists() {
        anyhow::bail!(
            "Host binary not found at {}. Run browser setup to download bridge assets first.",
            host_path.display()
        );
    }

    let manifest = json!({
        "name": NATIVE_HOST_NAME,
        "description": "Native host for Browser Agent Bridge (Chrome, managed by jcode)",
        "path": host_path.to_string_lossy(),
        "type": "stdio",
        "allowed_origins": [format!("chrome-extension://{}/", CHROME_EXTENSION_ID)]
    });
    let rendered = serde_json::to_string_pretty(&manifest)?;

    let manifest_path = chrome_manifest_install_path()?;
    if let Some(parent) = manifest_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let already_current = std::fs::read_to_string(&manifest_path)
        .map(|existing| existing == rendered)
        .unwrap_or(false);
    if !already_current {
        std::fs::write(&manifest_path, &rendered)?;
    }

    #[cfg(target_os = "windows")]
    register_chrome_windows_native_host(&manifest_path)?;

    Ok(!already_current)
}

/// Where the Chrome native messaging manifest lives on this platform.
fn chrome_manifest_install_path() -> Result<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        // On Windows the file can live anywhere; the registry points at it.
        Ok(chrome_host_manifest_path())
    }
    #[cfg(target_os = "linux")]
    {
        let home = dirs::home_dir().context("No home directory")?;
        Ok(home
            .join(".config")
            .join("google-chrome")
            .join("NativeMessagingHosts")
            .join(format!("{}.json", NATIVE_HOST_NAME)))
    }
    #[cfg(target_os = "macos")]
    {
        let home = dirs::home_dir().context("No home directory")?;
        Ok(home
            .join("Library")
            .join("Application Support")
            .join("Google")
            .join("Chrome")
            .join("NativeMessagingHosts")
            .join(format!("{}.json", NATIVE_HOST_NAME)))
    }
    #[cfg(not(any(target_os = "windows", target_os = "linux", target_os = "macos")))]
    {
        Err(anyhow::anyhow!(
            "Unsupported platform for Chrome native messaging"
        ))
    }
}

#[cfg(target_os = "windows")]
fn register_chrome_windows_native_host(manifest_path: &Path) -> Result<()> {
    let key = format!(
        r"HKCU\Software\Google\Chrome\NativeMessagingHosts\{}",
        NATIVE_HOST_NAME
    );
    let output = std::process::Command::new("reg")
        .args([
            "add",
            &key,
            "/ve",
            "/t",
            "REG_SZ",
            "/d",
            &manifest_path.to_string_lossy(),
            "/f",
        ])
        .output()
        .context("Failed to register Chrome native messaging host in Windows registry")?;
    if output.status.success() {
        return Ok(());
    }
    let stderr = String::from_utf8_lossy(&output.stderr);
    let stdout = String::from_utf8_lossy(&output.stdout);
    let details = if stderr.trim().is_empty() {
        stdout.trim().to_string()
    } else {
        stderr.trim().to_string()
    };
    anyhow::bail!(
        "Failed to register Chrome native messaging host in Windows registry: {}",
        details
    )
}

pub async fn inspect_chrome_status() -> Result<BrowserStatus> {
    let binary_installed = browser_binary_path().exists();
    let setup_complete = is_chrome_setup_complete();
    let responding = if binary_installed {
        check_browser_ping().await.unwrap_or(false)
    } else {
        false
    };
    let missing_actions = if responding {
        probe_bridge_missing_actions().await.unwrap_or_default()
    } else {
        Vec::new()
    };
    let compatible = responding && missing_actions.is_empty();
    let ready = responding && compatible;
    Ok(BrowserStatus {
        backend: "chrome_agent_bridge",
        browser: "chrome",
        setup_complete,
        binary_installed,
        responding,
        compatible,
        missing_actions,
        ready,
    })
}

pub async fn ensure_chrome_ready_noninteractive() -> Result<BrowserStatus> {
    let mut status = inspect_chrome_status().await?;
    if status.ready && !status.setup_complete && chrome_extension_dir().exists() {
        mark_chrome_setup_complete().ok();
        status.setup_complete = is_chrome_setup_complete();
    }
    Ok(status)
}

/// One-shot Chrome setup: download shared assets if needed, generate the
/// unpacked extension, register the native messaging host, then check the
/// live bridge. Loading the unpacked extension is a one-time manual step.
pub async fn ensure_chrome_setup() -> Result<String> {
    let mut log = String::new();
    std::fs::create_dir_all(browser_dir())?;

    if !browser_binary_path().exists() || !host_binary_path().exists() || !xpi_path().exists() {
        log.push_str("[1/4] Downloading browser bridge assets... ");
        match download_browser_binary().await {
            Ok(()) => log.push_str("done\n"),
            Err(e) => {
                log.push_str(&format!("failed: {}\n", e));
                return Ok(log);
            }
        }
    } else {
        log.push_str("[1/4] Browser bridge assets... already installed\n");
    }

    log.push_str("[2/4] Generating Chrome extension... ");
    let ext_dir = match generate_chrome_extension() {
        Ok(dir) => {
            log.push_str("done\n");
            dir
        }
        Err(e) => {
            log.push_str(&format!("failed: {}\n", e));
            return Ok(log);
        }
    };

    log.push_str("[3/4] Chrome native messaging host... ");
    match install_chrome_native_host_manifest() {
        Ok(true) => log.push_str("installed\n"),
        Ok(false) => log.push_str("already configured\n"),
        Err(e) => {
            log.push_str(&format!("failed: {}\n", e));
            return Ok(log);
        }
    }

    log.push_str("[4/4] Checking bridge connection... ");
    if check_browser_ping().await.unwrap_or(false) {
        log.push_str("connected!\n");
        mark_chrome_setup_complete().ok();
        log.push_str("\nSetup complete. The bridge is responding.\n");
        log.push_str(
            "Note: the bridge host serves whichever browser loaded the extension; keep it enabled in only one browser at a time.\n",
        );
    } else {
        log.push_str("not connected\n\n");
        log.push_str("One-time manual step to finish Chrome setup:\n");
        log.push_str("  1. Open chrome://extensions in Chrome\n");
        log.push_str("  2. Enable \"Developer mode\" (top right)\n");
        log.push_str(&format!(
            "  3. Click \"Load unpacked\" and select: {}\n",
            ext_dir.display()
        ));
        log.push_str(
            "  4. If the Firefox extension is also running, disable it there (the bridge host can serve only one browser at a time)\n",
        );
        log.push_str("Then re-run browser status to confirm readiness.\n");
    }

    Ok(log)
}

#[cfg(test)]
#[path = "browser_chrome_tests.rs"]
mod browser_chrome_tests;
